version: '3.5'
services:
  proxy: #代理網站
     container_name: apache_proxy
     image: poiuy999/apache_proxy
     restart: always #設定自動重開
     volumes:
      - ../../vhosts/:/etc/apache2/sites-customer/ #各網站的 vhost.conf
      - ../../base/proxy/:/var/www/html/ #預設網站的document_root
      - ../../certs/:/etc/letsencrypt/live/ #免費憑證存放位置
      - ../../logs/proxy:/var/log/apache2
     ports:
      - "80:80"
      - "443:443"
     networks:
      - default
      - front
  phpmyadmin:  #所有資料庫共用的phpMyAdmin
     container_name: apache_phpmyadmin
     image: poiuy999/apache_web73
     restart: always #設定自動重開
     volumes:
      - ../../base/phpmyadmin:/var/www/html/ #預設網站的document_root
      - ../../logs/phpmyadmin:/var/log/apache2
     networks:
      - default
      - backend
  manage_db:
    container_name: db_manage
    image: poiuy999/mysql57
    restart: always
    volumes:
      - ../../mysql/manage:/var/lib/mysql
      #- ../../install/mysql/:/docker-entrypoint-initdb.d/ #預執行的.sql檔
    environment:
      MYSQL_ROOT_PASSWORD: pwd_manage
      MYSQL_DATABASE: db_manage
      #MYSQL_USER: user_manage
      #MYSQL_PASSWORD: manage_
    networks:
      - default
      - backend
  manage_web:
     container_name: apache_manage
     depends_on:
      - manage_db
     image: poiuy999/apache_web73_public
     restart: always
     environment:
      - customer=manage
      - whoAmI=manage
     volumes:
      - ../../base/manage:/var/www/html
      - ../../logs/manage:/var/log/apache2
      - ../../workdir:/var/www/workdir
      - /var/run/docker.sock:/var/run/docker.sock
     networks:
      - default
      - front
networks:
    default:
    front:
        external: true
        name: front
    backend:
        external: true
        name: backend