version: '3.5'
services:
  db:
    container_name: db_${customer}
    image: poiuy999/mysql57
    restart: always
    volumes:
      - ../../mysql/${customer}:/var/lib/mysql
      #- ../../install/mysql/:/docker-entrypoint-initdb.d/ #預執行的.sql檔
    environment:
      MYSQL_ROOT_PASSWORD: pwd_${customer}
      MYSQL_DATABASE: db_${customer}
      MYSQL_USER: user_${customer}
      MYSQL_PASSWORD: ${password}
    networks:
      - default
      - backend
  web:
     container_name: web_${customer}
     depends_on:
      - db
     image: poiuy999/apache_web56
     restart: always
     environment:
      - customer=${customer}
      - whoAmI=${customer}
     volumes:
      - ../../html/${customer}:/var/www/html
      - ../../logs/${customer}:/var/log/apache2
     networks:
      - default
      - front
networks:
    default:
    front:
        external: true
        name: front
    backend:
        external: true
        name: backend